name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production
        
      - name: Show dist folder (debug)
        run: ls -R dist/asanZindegi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-browser
          path: dist/asanZindegi/browser

      - name: Upload package files
        uses: actions/upload-artifact@v4
        with:
          name: package-files
          path: |
            package.json
            package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-browser
          path: dist-browser

      - name: Download package files
        uses: actions/download-artifact@v4
        with:
          name: package-files
          path: package-files

      - name: Show downloaded files (debug)
        run: ls -R

      - name: Deploy dist to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ASANZINDEGI_HOST }}
          username: ${{ secrets.ASANZINDEGI_USER }}
          password: ${{ secrets.ASANZINDEGI_PASSWORD }}
          local-dir: dist-browser/
          server-dir: /asanzindegi/browser/
          dangerous-clean-slate: true

      - name: Deploy package.json to cPanel root
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ASANZINDEGI_HOST }}
          username: ${{ secrets.ASANZINDEGI_USER }}
          password: ${{ secrets.ASANZINDEGI_PASSWORD }}
          local-dir: package-files/
          server-dir: /
          dangerous-clean-slate: false
